# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/build

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Prepare
          command: mkdir -p ~/reports

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Codecov dependencies
          command: npm install --save-dev codecov

      - run:
          name: Run linter
          command: npm run lint:ci -- --output-file ~/reports/eslint/results.xml

      - run:
          name: Run tests
          command: JEST_JUNIT_OUTPUT=~/reports/jest/results.xml npm run test:ci

      - run:
          name: Report to codecov.io
          command: ./node_modules/codecov/bin/codecov

      - store_test_results:
          path: ~/reports

      - store_artifacts:
          path: ~/reports

      - store_artifacts:
          path: coverage
